# Generated by Django 5.2.1 on 2025-06-13 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('counsel_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('consel_history', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'consult_log',
            },
        ),
    ]
