# Generated by Django 5.2.1 on 2025-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
